version = 1

[[analyzers]]
name = "rust"
enabled = true

  [analyzers.meta]
  msrv = "stable"

[[analyzers]]
name = "scala"
enabled = true

[[analyzers]]
name = "terraform"
enabled = true

[[analyzers]]
name = "secrets"
enabled = true

[[analyzers]]
name = "ruby"
enabled = true

[[analyzers]]
name = "docker"
enabled = true

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_root = "github.com/dhrubasaha08/codespace"
  dependencies_vendored = true

[[analyzers]]
name = "ansible"
enabled = true

[[analyzers]]
name = "test-coverage"
enabled = true

[[analyzers]]
name = "sql"
enabled = true

[[analyzers]]
name = "shell"
enabled = true

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "php"
enabled = true

[[analyzers]]
name = "java"
enabled = true

  [analyzers.meta]
  runtime_version = "17"

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = [
    "react",
    "angular",
    "vue",
    "ember",
    "meteor",
    "angularjs"
  ]

[[analyzers]]
name = "csharp"
enabled = true

[[transformers]]
name = "prettier"
enabled = true

[[transformers]]
name = "dotnet-format"
enabled = true

[[transformers]]
name = "google-java-format"
enabled = true

[[transformers]]
name = "php-cs-fixer"
enabled = true

[[transformers]]
name = "autopep8"
enabled = true

[[transformers]]
name = "standardjs"
enabled = true

[[transformers]]
name = "yapf"
enabled = true

[[transformers]]
name = "isort"
enabled = true

[[transformers]]
name = "black"
enabled = true

[[transformers]]
name = "rustfmt"
enabled = true

[[transformers]]
name = "scalafmt"
enabled = true

[[transformers]]
name = "rubocop"
enabled = true

[[transformers]]
name = "standardrb"
enabled = true

[[transformers]]
name = "gofumpt"
enabled = true

[[transformers]]
name = "gofmt"
enabled = true